source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
xcodeproj '/Users/nissivieiramiranda/Documents/Nissi_iOS_Apps/GitHub projects/Demo Shop/Demo Shop/Demo Shop.xcodeproj'
pod 'Parse'
link_with 'Demo Shop', 'Demo ShopTests'