source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
xcodeproj '/Users/nissivieiramiranda/Documents/Nissi_iOS_Apps/GitHub projects/Demo Shop/Demo Shop/Demo Shop.xcodeproj'
pod 'Stripe'
pod 'MBProgressHUD', '~> 0.9.2'
link_with 'Demo Shop'